### ISSUE TITLE
[Tracking Issue] train.py should be modular

### ISSUE THREAD

**Issue by duk3luk3** [duk3luk3/beepo#1]
Separate issues / PRs can be made for these issues:

- [ ] Modularise the code in `train.py`
- [ ] Separate "game loop" (the `while True:`) out of `train.py` into (?) `main.py`
- [ ] Turn hardcoded options (`koch_length`, `cps`) into  command line parameters using argparse or docopt
